name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: List directory contents (for debugging)
      run: ls -R

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: . 
        name: github-pages
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
      with:
          artifact_name: github-pages
